import type { Metadata } from 'next'
import { Merriweather } from 'next/font/google'
import './globals.css'

const inter = Merriweather({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Romancer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
