import type { Metadata } from 'next'
import { Merriweather } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from './providers'

const inter = Merriweather({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Romancer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body
          className={`${inter.className} bg-[#f7f5f3] min-h-screen min-w-screen text-lg`}
        >
          {children}
        </body>
      </NextAuthProvider>
    </html>
  )
}

// #E3DBD4
